import React from "react";
  import { CgHjuvWgtzG, CsQZVMk8fSz, C21YNweH1wT, Ck2tLMgzTOJ, Czc0XmH6Tpp, CSgN5R2EOqS, C3u7gpFLrcl, C3H1jIfwe3K, CEttXT9wjw0, CqhDpLMMgc5, CYlbmsAfQkK, CVn7831SbRR, Cb3Kc7OOx8i, CSCqGwpFMsg, Cbx7Sqv698P, Cmj79bCbTbq, Ckg1m9QuOn4, CEZylMpaPkh, CQdUi6B3ike, ChQU5LE2DxT } from "./randomStyles.module.scss"
  import randomStyles from "./randomStyles.module.scss";
  
  console.log(randomStyles['CgHjuvWgtzG'])
console.log(randomStyles['CsQZVMk8fSz'])
console.log(randomStyles['C21YNweH1wT'])
console.log(randomStyles['Ck2tLMgzTOJ'])
console.log(randomStyles['Czc0XmH6Tpp'])
console.log(randomStyles['CSgN5R2EOqS'])
console.log(randomStyles['C3u7gpFLrcl'])
console.log(randomStyles['C3H1jIfwe3K'])
console.log(randomStyles['CEttXT9wjw0'])
console.log(randomStyles['CqhDpLMMgc5'])
console.log(randomStyles['CYlbmsAfQkK'])
console.log(randomStyles['CVn7831SbRR'])
console.log(randomStyles['Cb3Kc7OOx8i'])
console.log(randomStyles['CSCqGwpFMsg'])
console.log(randomStyles['Cbx7Sqv698P'])
console.log(randomStyles['Cmj79bCbTbq'])
console.log(randomStyles['Ckg1m9QuOn4'])
console.log(randomStyles['CEZylMpaPkh'])
console.log(randomStyles['CQdUi6B3ike'])
console.log(randomStyles['ChQU5LE2DxT'])
  export const App = () => {
    return <div></div>;
  }
  
    console.log(randomStyles.notExistClass)
    console.log(CgHjuvWgtzG)
console.log(CsQZVMk8fSz)
console.log(C21YNweH1wT)
console.log(Ck2tLMgzTOJ)
console.log(Czc0XmH6Tpp)
console.log(CSgN5R2EOqS)
console.log(C3u7gpFLrcl)
console.log(C3H1jIfwe3K)
console.log(CEttXT9wjw0)
console.log(CqhDpLMMgc5)
console.log(CYlbmsAfQkK)
console.log(CVn7831SbRR)
console.log(Cb3Kc7OOx8i)
console.log(CSCqGwpFMsg)
console.log(Cbx7Sqv698P)
console.log(Cmj79bCbTbq)
console.log(Ckg1m9QuOn4)
console.log(CEZylMpaPkh)
console.log(CQdUi6B3ike)
console.log(ChQU5LE2DxT)